#!/usr/bin/node
'use strict';
let _ = require('lodash');
let child_process = require('child_process');
let os = require('os');
let yargs = require('yargs');

yargs
    .usage('Usage:\n  $0 <command> [options]')
    .command({
        command: 'deploy <server>',
        description: 'Deploys Hapili to a target server, specified by its dns name or ip address.',
        handler: argv => {
            let server = argv.server;
            if (!server) {
                console.error('Which server?');
                return process.exit(1);
            }

            var args = ['-rv', '--exclude-from=.rsync-exclude', '.', server + ':/opt/hapili'];
            var child = child_process.execFile('rsync', args, function(error, stdout, stderr) {
                if (stdout) {
                    console.info(stdout);
                }
                if (stderr) {
                    console.error(stderr);
                }
                if (error) {
                    console.error(error);
                    return process.exit(1);
                }
                console.info('ok.');
            });
        },
    })
    .command({
        command: 'server',
        description: 'Run Hapili as a master server, and start the web server for access to the user interface.',
        builder: {
        },
        handler: argv => {
            return require('./hapili-server.js');
        },
    })
    .command({
        command: 'node',
        description: 'Run Hapili as a member node.',
        builder: {
        },
        handler: argv => {
            return require('./hapili-node.js');
        },
    })
    .option('arch', {
        description: 'Override the system os/arch identifier.',
        default: os.arch() + '|' + os.platform(),
    })
    .option('log.level', {
        alias: ['ll'],
        description: 'Set the default logging output level.',
        choices: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
        default: 'info',
    })
    .demandCommand()
    .help('help')
    .alias('help', 'h')
    .wrap(yargs.terminalWidth())
    .argv;
