#!/usr/bin/node
'use strict';
let _ = require('lodash');
let os = require('os');
let yargs = require('yargs');

yargs
    .usage('Usage:\n  $0 <command> [options]')
    .commandDir('./lib/cli')
    .option('arch', {
        description: 'Override the system os/arch identifier.',
        default: os.arch() + '|' + os.platform(),
    })
    .option('log.level', {
        alias: ['ll'],
        description: 'Set the default logging output level.',
        choices: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
        default: 'info',
    })
    .demandCommand(1, 'Which command?')
    .help('help')
    .alias('help', 'h')
    .wrap(yargs.terminalWidth())
    .argv;
